// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://samoturehtpnvbyatisc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhbW90dXJlaHRwbnZieWF0aXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNTY2MzIsImV4cCI6MjA1MTgzMjYzMn0.ttvBLFarLn3BymOGxZ7bcAOTXYfKcPuwEkJAuV2jsn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);